#!/usr/bin/env bash
# Supplementary campaign passes for the dual algorithms DPaC and DHPaC
# (docs/PIANO_PARTE_COMPUTAZIONALE.md section 3: DPaC is the general dual of
# PaC, DHPaC the general dual of HPaC). They are already covered by the
# correctness/differential suite in tests/test_main.cpp; this script adds
# them to the same official campaign instance sets used for PaC/HPaC/RaC
# timing, reusing the instances already generated by
# tools/run_official_campaigns.sh (no regeneration). DPaC shares PaC's
# O(n^2)-ish scaling (empirically confirmed: ~22s at n=20000, matching PaC),
# so it is scoped to the same size cutoff as PaC; DHPaC is heap-based like
# HPaC and is run at full scale, still under the same timeout/memory guard.
#
# Runs on a separate CPU core from tools/run_official_campaigns.sh so both
# can proceed concurrently without contention.
set -euo pipefail
cd "$(dirname "$0")/.."

BIN=build/pcf_benchmark
RUN="python3 tools/run_benchmark.py"
MEM_LIMIT_KIB=8000000
TIMEOUT_S=300
CORE=1
TASKSET=""
if command -v taskset >/dev/null 2>&1; then TASKSET="taskset -c ${CORE}"; fi

run() {
  local dir=$1 algs=$2 reps=$3 cid=$4 seed=$5
  local out=results/raw/${cid}_${algs//,/-}.csv
  echo "=== ${cid} :: ${algs} (${reps} reps) on ${dir} -> ${out} ==="
  ${TASKSET} ${RUN} --binary "${BIN}" --instances "${dir}" --output "${out}" \
    --algorithms "${algs}" --repetitions "${reps}" --campaign-id "${cid}" \
    --shuffle-seed "${seed}" --timeout-seconds "${TIMEOUT_S}" --memory-limit-kib "${MEM_LIMIT_KIB}"
}

wait_for_dir() {
  local dir=$1
  while [ ! -d "${dir}" ]; do
    echo "waiting for ${dir} to be generated by run_official_campaigns.sh..."
    sleep 30
  done
}

campaign_b()  { run instances/campaign_b dpac,dhpac 11 campaign_b 5; }

campaign_c()  {
  run instances/campaign_c dhpac 3 campaign_c 6
  wait_for_dir "instances/campaign_c_n20000_subset"
  run instances/campaign_c_n20000_subset dpac 3 campaign_c 6
}

campaign_d()  {
  for shape in path binary star; do
    wait_for_dir "instances/campaign_d_${shape}"
    run "instances/campaign_d_${shape}" dhpac 3 "campaign_d_${shape}" 7
    run "instances/campaign_d_${shape}_pac_subset" dpac 3 "campaign_d_${shape}" 7
  done
}

campaign_e() {
  for topo in in out; do
    wait_for_dir "instances/campaign_e_${topo}"
    run "instances/campaign_e_${topo}" dhpac 3 "campaign_e_${topo}" 8
  done
}

mkdir -p results/raw
targets=("$@")
[ ${#targets[@]} -eq 0 ] && targets=(b c d e)
for target in "${targets[@]}"; do
  "campaign_${target}"
done
echo "=== dual-variant campaigns finished: $(date -u +%FT%TZ) ==="
