#!/usr/bin/env bash
# Supplementary campaign passes for the dual algorithms DPaC and DHPaC
# (docs/PIANO_PARTE_COMPUTAZIONALE.md section 3: DPaC is the general dual of
# PaC, DHPaC the general dual of HPaC). They are already covered by the
# correctness/differential suite in tests/test_main.cpp; this script adds
# them to the same official campaign instance sets used for PaC/HPaC/RaC
# timing, reusing the instances already generated by
# tools/run_official_campaigns.sh (no regeneration). DPaC shares PaC's
# O(n^2)-ish scaling (empirically confirmed: ~22s at n=20000, matching PaC),
# so it is scoped to the same size cutoff as PaC; DHPaC is heap-based like
# HPaC and is run at full scale, still under the same timeout/memory guard.
#
# Runs on a separate CPU core from tools/run_official_campaigns.sh so both
# can proceed concurrently without contention.
set -euo pipefail
cd "$(dirname "$0")/.."

BIN=build/pcf_benchmark
RUN="python3 tools/run_benchmark.py"
MEM_LIMIT_KIB=8000000
TIMEOUT_S=300
CORE=${PCF_CORE:-1}       # override per lane in tools/run_night_sweep.sh
TASKSET=""
if command -v taskset >/dev/null 2>&1; then TASKSET="taskset -c ${CORE}"; fi

run() {
  # run <instances-dir> <algorithms> <repetitions> <campaign-id> <shuffle-seed> [output-tag]
  local dir=$1 algs=$2 reps=$3 cid=$4 seed=$5 tag=${6:-}
  local out=results/raw/${cid}${tag:+_${tag}}_${algs//,/-}.csv
  echo "=== ${cid} :: ${algs} (${reps} reps) on ${dir} -> ${out} ==="
  ${TASKSET} ${RUN} --binary "${BIN}" --instances "${dir}" --output "${out}" \
    --algorithms "${algs}" --repetitions "${reps}" --campaign-id "${cid}" \
    --shuffle-seed "${seed}" --timeout-seconds "${TIMEOUT_S}" --memory-limit-kib "${MEM_LIMIT_KIB}"
}

wait_for_dir() {
  local dir=$1
  while [ ! -d "${dir}" ]; do
    echo "waiting for ${dir} to be generated by run_official_campaigns.sh..."
    sleep 30
  done
}

campaign_b()  { run instances/campaign_b dpac,dhpac 11 campaign_b 5; }

campaign_c()  {
  run instances/campaign_c dhpac 3 campaign_c 6
  wait_for_dir "instances/campaign_c_n10000_subset"
  run instances/campaign_c_n10000_subset dpac 2 campaign_c 6 n10000
  wait_for_dir "instances/campaign_c_n20000_subset"
  run instances/campaign_c_n20000_subset dpac 3 campaign_c 6 n20000
}

campaign_d()  {
  for shape in path binary; do
    wait_for_dir "instances/campaign_d_${shape}"
    run "instances/campaign_d_${shape}" dhpac 3 "campaign_d_${shape}" 7
    run "instances/campaign_d_${shape}_pac_subset" dpac 3 "campaign_d_${shape}" 7
  done
  # Star: DHPaC obeys the same preregistered n<=20000 cutoff as HPaC
  # (docs/EXPERIMENTAL_PLAN_V3.md, decision 5bis); no dual star pass beyond
  # that, and no DPaC star pass (the rebuilt star table reports PaC/HPaC/RaC).
  wait_for_dir "instances/campaign_d_star_small"
  run "instances/campaign_d_star_small" dhpac 3 "campaign_d_star" 7
}

campaign_e_in()  { wait_for_dir "instances/campaign_e_in";  run "instances/campaign_e_in"  dhpac 3 "campaign_e_in" 8; }
campaign_e_out() { wait_for_dir "instances/campaign_e_out"; run "instances/campaign_e_out" dhpac 3 "campaign_e_out" 8; }
campaign_e()     { campaign_e_in; campaign_e_out; }

mkdir -p results/raw
targets=("$@")
[ ${#targets[@]} -eq 0 ] && targets=(b c d e)
for target in "${targets[@]}"; do
  "campaign_${target}"
done
echo "=== dual-variant campaigns finished: $(date -u +%FT%TZ) ==="
